### ISSUE TITLE
Doesn't run at boot

### ISSUE THREAD

**Issue by tpcarmen** [ssaqua/ProximityService#11]
Would it be possible to add a "run at boot" setting? 

Right now I need to start it manually after each boot (or is this a bug, and it's already supposed to start at boot?)

**Comment by ssaqua** [comment]
Hello, it's not a feature at the moment but I have seen it being asked for enough times already so will consider adding it.

I do want to understand a bit more about the use case though. My assumption is that if someone wanted to run at boot automatically, it suggests they are running the service most of the time. Since the default mode while the proximity sensor is blocked is to prevent the device from sleeping, even though the screen is off they would have reduced battery life simply because the phone is never allowed to sleep. The app was never meant for keeping the device screen off for prolonged periods without some kind of background activity that the user is aware of.

That is the main reason that this is not a feature at the moment, but again, it is just based on my assumptions. I would definitely like to hear about other use cases that I might be overlooking.

**Comment by tpcarmen** [comment]
Maybe I'm using it wrong.

I'm using it to turn off the screen and prevent butt dialing when I flip the case closed. 

Terry

**Comment by ssaqua** [comment]
I would not recommend keeping the app on all the time, it's really meant for specific usages like keeping games/YouTube running in the background with the display off or if you just want a quick way to temporarily hide your screen.

If the service is active with a flip case closed for hours, the phone won't be able to automatically lock or optimize battery by entering Doze/App Standby. Only one of the modes in the app settings (AMOLED No WakeLock) would be suitable for this use case as it will allow the system screen timeout to happen normally.

**Comment by tpcarmen** [comment]
Thank you very much!

I know this wasn't your intended use but it seems to work very nicely for it.

Terry
